name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet le déclenchement manuel du workflow

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rouguii/python-app
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta.outputs.tags }}-latest
          labels: ${{ steps.meta.outputs.labels }}
    
  deploy_staging:
    name: Déployer sur la VM de staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Ajouter la clé SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
          
      - name: Déployer sur la VM de staging
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          STAGING_ENV: true
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.199.82.209 << 'EOF'
            echo "Déploiement dans l'environnement de staging..."
            echo "Récupération de l'image Docker..."
            docker pull rouguii/python-app:main-latest
            if [ "$(docker ps -q -f name=python-app-staging)" ]; then
              echo "Arrêt et suppression du conteneur existant..."
              docker stop python-app-staging
              docker rm python-app-staging
            fi
            echo "Lancement du conteneur Docker..."
            docker run -d --name python-app-staging -p 8089:8088 \
              -e DB_HOST=$DB_HOST \
              -e DB_PORT=$DB_PORT \
              -e DB_USER=$DB_USER \
              -e DB_PASSWORD=$DB_PASSWORD \
              -e DB_NAME=$DB_NAME \
              rouguii/python-app:main-latest
          EOF

  deploy_production:
    name: Déployer sur la VM de production
    runs-on: ubuntu-latest
    # Exécuter seulement lors d'un déclenchement manuel
    if: ${{ github.event_name == 'workflow_dispatch' }} 
    steps:
      - name: Ajouter la clé SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Déployer sur la VM de production
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.199.82.73 << 'EOF'
            echo "Déploiement dans l'environnement de production..."
            echo "Récupération de l'image Docker..."
            docker pull rouguii/python-app:main-latest
            if [ "$(docker ps -q -f name=python-app-production)" ]; then
              echo "Arrêt et suppression du conteneur existant..."
              docker stop python-app-production
              docker rm python-app-production
            fi
            echo "Lancement du conteneur Docker..."
            docker run -d --name python-app-production -p 8088:8088 \
              -e DB_HOST=$DB_HOST \
              -e DB_PORT=$DB_PORT \
              -e DB_USER=$DB_USER \
              -e DB_PASSWORD=$DB_PASSWORD \
              -e DB_NAME=$DB_NAME \
              rouguii/python-app:main-latest
          EOF
