name: Publish Docker image and deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and deploy to Azure VM
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4  # Mise à jour vers la dernière version
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Mise à jour vers la dernière version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4  # Mise à jour vers la dernière version
        with:
          images: rouguii/python-app
      
      #- name: Print Docker image tags
        #run: echo ${{ steps.meta.outputs.tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Mise à jour vers la dernière version
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4  # Utilisation de la version stable disponible
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Azure VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@172.201.227.175 << 'EOF'
            # Afficher les balises d'image pour le débogage
            echo "Docker images tags: ${{ steps.meta.outputs.tags }}"
            # Tirer la nouvelle image Docker
            docker pull rouguii/python-app:main
            # Exécuter le nouveau conteneur dans la vm
            docker run -d --name python-app -p 8088:8088 rouguii/python-app:main
          EOF
